version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./
    restart: always
    networks:
      - api
      - web
      - dashboard
      - blog
      - wordpress
      - influxdb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /var/run/docker.sock:/tmp/docker.sock
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

networks:
  api:
    external:
      name: almond_almond-network
  web:
    external:
      name: almond_almond-network
  dashboard:
    external:
      name: almond_almond-network
  wordpress:
    external:
      name: almond_almond-network
  influxdb:
    external:
      name: almond_almond-network
  blog:
    external:
      name: musings_musings-network
