version: '3'
services:
  proxy:
    build: ./
    networks:
      - api
      - web
    ports:
      - "80:80"

networks:
  api:
    external:
      name: almond-be_app-network
  web:
    external:
      name: almond-be_app-network
